### ISSUE TITLE
Convert Python module definitions to YAML syntax

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/pipelines-core#3]
Following security concerns raised by @Prepultrue, we decided to migrate the Python-based definitions to YAML as described at [https://arcana.readthedocs.io/en/develop/deployment.html#building](https://arcana.readthedocs.io/en/develop/deployment.html#building).

**Comment by tclose** [comment]
Would you mind having a look at this @Prepultrue?

**Comment by Prepultrue** [comment]
Sure

**Comment by tclose** [comment]
This has been implemented in recent merge
